version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
        update-types:
          - major
          - minor
          - patch
      minor-and-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    groups:
      actions:
        update-types:
          - minor
          - patch
